# Generated by Django 6.0 on 2026-01-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_vehicle_sale_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('busy', 'In Transit'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
