# Generated by Django 6.0 on 2026-01-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_mileage',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_condition',
            field=models.CharField(blank=True, help_text='Condition recorded at last return', max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('busy', 'In Transit'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
    ]
