# Generated by Django 6.0 on 2026-01-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_vehicle_current_mileage_vehicle_last_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
