# Generated by Django 6.0 on 2026-01-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_saleitem_commission_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('bank', 'Bank Transfer'), ('mobile', 'Mobile Money')], default='cash', max_length=20),
        ),
    ]
