# Generated by Django 6.0 on 2026-01-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Carrying capacity in kg', max_digits=10),
        ),
    ]
