# Generated by Django 5.0.1 on 2026-06-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_historicalsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Flat discount applied to this sale', max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Flat discount applied to this sale', max_digits=12),
        ),
    ]
