# Generated by Django 6.0.5 on 2026-09-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_historicalsale_discount_sale_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
