# Generated by Django 6.0.5 on 2026-06-27 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_taxpayment'),
        ('sales', '0012_historicalsale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, help_text='Invoice the customer paid against', max_length=50)),
                ('customer_name', models.CharField(blank=True, help_text='Snapshot of the customer name', max_length=200)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Invoice total at record time', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Figure shown on the receipt', max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance still owed after this receipt', max_digits=12)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='payment_receipts/%Y/%m/')),
                ('payment_date', models.DateField()),
                ('reference', models.CharField(blank=True, help_text='Mobile money txn ID, bank ref, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='Finance user who logged the receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_receipts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_receipts', to='sales.customer')),
                ('issued_by', models.ForeignKey(blank=True, help_text='Staff who issued the invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_invoice_receipts', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_receipts', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
