# Generated by Django 6.0.5 on 2026-06-27 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_paymentreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. CRDB - Main Account', max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('branch', models.CharField(blank=True, help_text='Bank branch', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='bank',
            field=models.ForeignKey(blank=True, help_text='Bank account the money was taken from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.bankaccount'),
        ),
    ]
