# Generated by Django 5.2.15 on 2026-09-07 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_bankaccount_expense_bank'),
        ('inventory', '0016_alter_branch_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('casual_labour', 'Casual Labour'), ('salary_advance', 'Salary Advance'), ('customer_refund', 'Customer Refund'), ('utility', 'Utility Bill'), ('rent', 'Rent'), ('transport', 'Transport / Fuel'), ('licence', 'Licence / Permit'), ('loan_repayment', 'Loan Repayment'), ('other', 'Other')], default='other', max_length=30)),
                ('payee', models.CharField(help_text='Person or organisation paid', max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('mobile_money', 'Mobile Money')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Check no, transaction ID, etc.', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='other_payments/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(blank=True, help_text='Account the money left, if not cash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_payments', to='finance.bankaccount')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_payments', to='inventory.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('in', 'Cash In (Top-up)'), ('out', 'Cash Out (Payment)')], default='out', max_length=3)),
                ('voucher_number', models.CharField(blank=True, help_text='Auto-generated on save, e.g. PC-000123', max_length=20, unique=True)),
                ('payee', models.CharField(blank=True, help_text='Who received the cash', max_length=150)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, help_text='Receipt no, slip no, etc.', max_length=100)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='petty_cash/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(blank=True, help_text='Account a top-up was drawn from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_topups', to='finance.bankaccount')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash', to='inventory.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash', to='finance.expensecategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petty Cash Transaction',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
