# Generated by Django 5.2.15 on 2026-09-07 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_otherpayment_pettycashtransaction'),
        ('inventory', '0016_alter_branch_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='The order this payment settles', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='inventory.purchaseorder'),
        ),
    ]
