# Generated by Django 5.2.15 on 2026-09-07 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_supplierpayment_purchase_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierpayment',
            options={'ordering': ['-payment_date', '-id']},
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved or rejected it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_supplier_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='decision_note',
            field=models.TextField(blank=True, help_text="Admin's reason, most useful on a rejection"),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('paid', 'Paid'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
    ]
