# Generated by Django 5.2.15 on 2026-09-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_settle_existing_supplier_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='cashier_note',
            field=models.TextField(blank=True, help_text="Cashier's answer to a rejection"),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
