# Generated by Django 5.2.15 on 2026-09-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_supplierpayment_cashier_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='from_credit',
            field=models.BooleanField(db_index=True, default=False, help_text="Settled from the supplier's credit rather than fresh money"),
        ),
    ]
