# Generated by Django 5.2.15 on 2026-09-07 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_supplierpayment_from_credit'),
        ('inventory', '0016_alter_branch_options_alter_category_options_and_more'),
        ('sales', '0014_alter_customer_options_alter_quotation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('sale_date', models.DateField(db_index=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('settlement', models.CharField(choices=[('paid', 'Paid'), ('part_paid', 'Part Paid'), ('credit', 'On Credit')], db_index=True, default='credit', max_length=12)),
                ('methods', models.CharField(blank=True, help_text="How it was paid, e.g. 'Cash, Mobile Money'", max_length=120)),
                ('sale_status', models.CharField(blank=True, help_text="The sale's own state at last sync", max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('queried', 'Queried')], db_index=True, default='pending', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, help_text="Accountant's note, most useful on a query")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_ledger_entries', to='inventory.branch')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_sales_entries', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='sales.sale')),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Ledger Entry',
                'verbose_name_plural': 'Sales Ledger Entries',
                'ordering': ['-sale_date', '-id'],
            },
        ),
    ]
