# Generated by Django 5.2.15 on 2026-09-07 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_salesledgerentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesledgerentry',
            name='commission_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesledgerentry',
            name='confirmed_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Money the accountant has confirmed as received', max_digits=12),
        ),
        migrations.AddField(
            model_name='salesledgerentry',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesledgerentry',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_sales_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesledgerentry',
            name='confirmed_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mobile', 'Mobile Money'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='salesledgerentry',
            name='confirmed_reference',
            field=models.CharField(blank=True, help_text='Bank ref, transaction ID, cheque no', max_length=100),
        ),
        migrations.AddField(
            model_name='salesledgerentry',
            name='cost_of_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='What the goods cost us, at the time of the sale', max_digits=12),
        ),
        migrations.AddField(
            model_name='salesledgerentry',
            name='invoice_document',
            field=models.FileField(blank=True, help_text='The invoice, attached when the payment is confirmed', null=True, upload_to='sales_invoices/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='salesledgerentry',
            name='payment_status',
            field=models.CharField(choices=[('awaiting', 'Awaiting Confirmation'), ('confirmed', 'Payment Confirmed')], db_index=True, default='awaiting', max_length=10),
        ),
    ]
