# Generated by Django 5.2.15 on 2026-09-07 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_salesledgerentry_commission_total_and_more'),
        ('inventory', '0017_alter_purchaseorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.TextField(help_text='What the money is for')),
                ('status', models.CharField(choices=[('pending', 'Awaiting Approval'), ('approved', 'Approved - To Issue'), ('rejected', 'Rejected'), ('issued', 'Issued')], db_index=True, default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, help_text="Admin's reason, most useful on a rejection")),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('issue_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_petty_cash_requests', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_requests', to='inventory.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_requests', to='finance.expensecategory')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_petty_cash_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_requests', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, help_text='The float movement this request produced', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='finance.pettycashtransaction')),
            ],
            options={
                'verbose_name': 'Petty Cash Request',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
