# Generated by Django 5.2.15 on 2026-09-13 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_pettycashrequest'),
        ('inventory', '0017_alter_purchaseorder_status'),
        ('sales', '0014_alter_customer_options_alter_quotation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Auto-generated from the kind if left blank, e.g. CU-0012', max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('bank', 'Bank Account'), ('cash', 'Cash Book'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('income', 'Income'), ('expense', 'Expense'), ('asset', 'Other Asset'), ('liability', 'Other Liability'), ('tax', 'Tax'), ('equity', 'Equity')], db_index=True, max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Balance brought forward when the books began', max_digits=14)),
                ('opening_side', models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], help_text="Which side the opening balance sits on; defaults to the ledger's normal side", max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger', to='finance.bankaccount')),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger', to='sales.customer')),
                ('supplier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Ledger Account',
                'ordering': ['kind', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment'), ('contra', 'Contra'), ('journal', 'Journal')], db_index=True, max_length=10)),
                ('number', models.CharField(blank=True, help_text='Auto-generated on post, e.g. RV-000012', max_length=20, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Total of the debit side (which equals the credit side)', max_digits=14)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('cancelled', 'Cancelled')], db_index=True, default='posted', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_vouchers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('narration', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='finance.ledgeraccount')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.voucher')),
            ],
            options={
                'ordering': ['voucher', 'side', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Invoice number or PO number', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_allocations', to='inventory.purchaseorder')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_allocations', to='sales.sale')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.voucherline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GeneralLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('voucher_type', models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment'), ('contra', 'Contra'), ('journal', 'Journal')], max_length=10)),
                ('voucher_number', models.CharField(db_index=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='finance.ledgeraccount')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_entries', to='finance.voucher')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gl_entry', to='finance.voucherline')),
            ],
            options={
                'verbose_name': 'General Ledger Entry',
                'verbose_name_plural': 'General Ledger Entries',
                'ordering': ['date', 'id'],
            },
        ),
    ]
