# Generated by Django 5.2.15 on 2026-09-13 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_general_ledger'),
        ('inventory', '0017_alter_purchaseorder_status'),
        ('sales', '0014_alter_customer_options_alter_quotation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledgerentry',
            name='reference',
            field=models.CharField(blank=True, db_index=True, help_text='Invoice number of a Sales/Purchase voucher', max_length=50),
        ),
        migrations.AddField(
            model_name='voucher',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='efd_number',
            field=models.CharField(blank=True, db_index=True, help_text='EFD receipt (RCT) number, kept apart from the invoice number', max_length=50),
        ),
        migrations.AddField(
            model_name='voucher',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, help_text="Our sales invoice number, or the supplier's invoice number", max_length=50),
        ),
        migrations.AddField(
            model_name='voucher',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT-exclusive amount', max_digits=14),
        ),
        migrations.AddField(
            model_name='voucher',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank'), ('credit', 'Credit'), ('partly_paid', 'Partly Paid')], help_text='Read off the lines at posting', max_length=12),
        ),
        migrations.AddField(
            model_name='voucher',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The part of the total on tax ledgers', max_digits=14),
        ),
        migrations.AddField(
            model_name='voucherallocation',
            name='voucher',
            field=models.ForeignKey(blank=True, help_text='The Sales or Purchase voucher this settles', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='finance.voucher'),
        ),
        migrations.AlterField(
            model_name='generalledgerentry',
            name='voucher_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('receipt', 'Receipt'), ('payment', 'Payment'), ('contra', 'Contra'), ('journal', 'Journal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('receipt', 'Receipt'), ('payment', 'Payment'), ('contra', 'Contra'), ('journal', 'Journal')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='voucherallocation',
            name='reference',
            field=models.CharField(help_text='Invoice number, PO number or voucher number', max_length=50),
        ),
    ]
