# Generated by Django 6.0.5 on 2026-10-04 19:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_invoice_vouchers'),
        ('inventory', '0017_alter_purchaseorder_status'),
        ('sales', '0014_alter_customer_options_alter_quotation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO code, e.g. USD', max_length=10, unique=True, verbose_name='Currency code')),
                ('name', models.CharField(max_length=60)),
                ('symbol', models.CharField(blank=True, help_text='Shown next to amounts, e.g. $', max_length=10)),
                ('is_base', models.BooleanField(default=False, help_text='The General Ledger, trial balance and all reports are kept in this currency', verbose_name='Base (reporting) currency')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['-is_base', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField(db_index=True, verbose_name='Date')),
                ('rate', models.DecimalField(decimal_places=6, help_text='Units of the base currency for 1 unit of this currency, e.g. 1 USD = 2650.00 TZS', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Rate')),
                ('note', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['currency', '-rate_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Used in voucher numbers, e.g. 2026 or 2025-26', max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True, help_text='Default financial year for new vouchers')),
                ('is_closed', models.BooleanField(default=False, help_text='Closed years reject postings unless the user is authorised')),
                ('lock_date', models.DateField(blank=True, help_text='Postings dated on or before this date are locked for normal users', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Financial year',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sales', 'Customer invoice'), ('purchase', 'Supplier bill'), ('opening', 'Opening balance')], db_index=True, max_length=10)),
                ('invoice_number', models.CharField(db_index=True, max_length=60)),
                ('efd_number', models.CharField(blank=True, db_index=True, max_length=60)),
                ('invoice_date', models.DateField(db_index=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partly_paid', 'Partly paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['invoice_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(max_length=10)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voucher number sequence',
            },
        ),
        migrations.CreateModel(
            name='VoucherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('prefix', models.CharField(help_text='Used in voucher numbers, e.g. SV', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Voucher type',
                'ordering': ['pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['-date', '-id'], 'permissions': [('post_voucher', 'Can post vouchers to the General Ledger'), ('cancel_voucher', 'Can cancel draft vouchers'), ('reverse_voucher', 'Can reverse posted vouchers'), ('post_closed_period', 'Can post into closed / locked financial periods')]},
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_entries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_entries', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='foreign_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='foreign_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_entries', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='account_type',
            field=models.CharField(blank=True, choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], db_index=True, help_text='Which side of the trial balance this ledger belongs to; taken from the kind when left blank', max_length=10),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='category',
            field=models.CharField(blank=True, choices=[('CURRENT_ASSET', 'Current asset'), ('FIXED_ASSET', 'Fixed asset'), ('OTHER_ASSET', 'Other asset'), ('CURRENT_LIABILITY', 'Current liability'), ('LONG_TERM_LIABILITY', 'Long-term liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('OTHER_INCOME', 'Other income'), ('COST_OF_SALES', 'Cost of sales'), ('OPERATING_EXPENSE', 'Operating expense'), ('OTHER_EXPENSE', 'Other expense')], max_length=25),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='is_customer_control',
            field=models.BooleanField(default=False, help_text='Accounts Receivable control — customer sub-ledgers hang under it', verbose_name='Customer control account'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='is_group',
            field=models.BooleanField(default=False, help_text='Group accounts organise the chart and are never posted to', verbose_name='Group / header account'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='is_supplier_control',
            field=models.BooleanField(default=False, help_text='Accounts Payable control — supplier sub-ledgers hang under it', verbose_name='Supplier control account'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='A group account, or a customer/supplier control account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='vat_kind',
            field=models.CharField(blank=True, choices=[('', 'Not a VAT ledger'), ('OUTPUT', 'Output VAT (sales)'), ('INPUT', 'Input VAT (purchases)')], default='', max_length=10, verbose_name='VAT ledger type'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='base_total_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='voucher',
            name='base_total_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='voucher',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='Units of the base currency for 1 unit of the voucher currency', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AddField(
            model_name='voucher',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reference',
            field=models.CharField(blank=True, help_text='Cheque number, external reference, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='finance.voucher'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='sequence_number',
            field=models.PositiveIntegerField(default=0, help_text='The sequence this number came from'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='voucher',
            name='total_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='voucher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='vat_account',
            field=models.ForeignKey(blank=True, help_text='Output VAT ledger (sales) or Input VAT ledger (purchases)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vat_vouchers', to='finance.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='voucherallocation',
            name='allocated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='voucherallocation',
            name='allocated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucherallocation',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='`amount` converted to the base currency', max_digits=18),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_lines', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_lines', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='generalledgerentry',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='generalledgerentry',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='generalledgerentry',
            name='reference',
            field=models.CharField(blank=True, db_index=True, help_text='Invoice number / EFD receipt number / external reference', max_length=150),
        ),
        migrations.AlterField(
            model_name='generalledgerentry',
            name='voucher_number',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='number',
            field=models.CharField(blank=True, help_text='Assigned when the draft is first saved, e.g. RV-2026-000012', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], db_index=True, default='posted', max_length=10),
        ),
        migrations.AlterField(
            model_name='voucherallocation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='voucherallocation',
            name='reference',
            field=models.CharField(help_text='Invoice number, PO number or voucher number', max_length=60),
        ),
        migrations.AlterField(
            model_name='voucherline',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.CreateModel(
            name='AccountingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('EDITED', 'Edited'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed'), ('ALLOCATED', 'Allocated'), ('UNALLOCATED', 'Unallocated'), ('DELETED', 'Deleted'), ('SETTINGS', 'Settings changed')], db_index=True, max_length=20)),
                ('voucher_number', models.CharField(blank=True, db_index=True, max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='finance.voucher')),
            ],
            options={
                'verbose_name': 'Accounting audit entry',
                'verbose_name_plural': 'Accounting audit trail',
                'ordering': ['-timestamp', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year_start', models.DateField(help_text='Start of the current financial year')),
                ('financial_year_end', models.DateField(help_text='End of the current financial year')),
                ('voucher_number_padding', models.PositiveSmallIntegerField(default=6, help_text='Digits used for the sequence, e.g. 6 -> 000001', validators=[django.core.validators.MinValueValidator(1)])),
                ('include_financial_year_in_number', models.BooleanField(default=True, help_text='Include the financial year code in voucher numbers (SV-2026-000001)')),
                ('reset_sequence_each_year', models.BooleanField(default=True, help_text='Restart sequential numbering for every financial year')),
                ('number_separator', models.CharField(default='-', max_length=3)),
                ('efd_enabled', models.BooleanField(default=True, verbose_name='EFD receipts in use')),
                ('efd_serial_number', models.CharField(blank=True, max_length=100, verbose_name='EFD serial number')),
                ('efd_duplicate_policy', models.CharField(choices=[('WARN', 'Warn on a duplicate EFD receipt number'), ('BLOCK', 'Block a duplicate EFD receipt number'), ('ALLOW', 'Allow duplicates silently')], default='WARN', max_length=10)),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, verbose_name='Default VAT rate (%)')),
                ('period_lock_date', models.DateField(blank=True, help_text='Transactions dated on or before this date need the post-into-closed-period permission', null=True)),
                ('allow_backdated_entries', models.BooleanField(default=True, help_text='Allow transaction dates earlier than today (subject to financial-year locking)', verbose_name='Allow prior-dated entries')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.ledgeraccount')),
                ('default_cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.ledgeraccount')),
                ('default_input_vat_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.ledgeraccount')),
                ('default_output_vat_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.ledgeraccount')),
                ('default_purchase_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.ledgeraccount')),
                ('default_sales_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.ledgeraccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accounting configuration',
                'verbose_name_plural': 'Accounting configuration',
            },
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='finance.currency'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency of this ledger (blank = base currency). A foreign-currency bank account can only be used on vouchers in the same currency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='finance.currency'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency the amounts are entered in (blank = base currency)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='finance.currency'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['account_type'], name='finance_led_account_ad4ef1_idx'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_rates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='finance.currency'),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='financial_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='finance.financialyear'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='financial_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='finance.financialyear'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentry',
            index=models.Index(fields=['account', 'date'], name='finance_gen_account_b08eee_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentry',
            index=models.Index(fields=['customer', 'date'], name='finance_gen_custome_1a6cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentry',
            index=models.Index(fields=['supplier', 'date'], name='finance_gen_supplie_63c298_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['voucher_type', 'status'], name='finance_vou_voucher_e51d26_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['date', 'voucher_type'], name='finance_vou_date_55c7aa_idx'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_invoices', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_invoices', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voucher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='finance.voucher'),
        ),
        migrations.AddField(
            model_name='voucherallocation',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='The invoice register row this settles', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='vouchernumbersequence',
            name='financial_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sequences', to='finance.financialyear'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('currency', 'rate_date'), name='exchangerate_unique_per_day'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('customer__isnull', False), ('supplier__isnull', False), _connector='OR'), name='invoice_has_party'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('customer__isnull', False)), fields=('kind', 'customer', 'invoice_number'), name='unique_customer_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier__isnull', False)), fields=('kind', 'supplier', 'invoice_number'), name='unique_supplier_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='vouchernumbersequence',
            constraint=models.UniqueConstraint(fields=('voucher_type', 'financial_year'), name='unique_sequence_per_type_year'),
        ),
    ]
