# Generated by Django 6.0.5 on 2026-10-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_open_the_books'),
        ('inventory', '0017_alter_purchaseorder_status'),
        ('sales', '0014_alter_customer_options_alter_quotation_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_customer_invoice_number',
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_supplier_invoice_number',
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('customer__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('kind', 'customer', 'invoice_number'), name='unique_customer_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('kind', 'supplier', 'invoice_number'), name='unique_supplier_invoice_number'),
        ),
    ]
