# Generated by Django 5.2.15 on 2026-10-07 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_remove_invoice_unique_customer_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='sales_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='finance.salesledgerentry'),
        ),
    ]
