# Generated by Django 5.0.1 on 2026-01-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Umoja Hardware', max_length=100)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='Percentage (e.g. 18.00)', max_digits=5)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
            ],
        ),
    ]
