# Generated by Django 6.0.5 on 2026-06-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='tin',
            field=models.CharField(blank=True, help_text='Taxpayer Identification Number', max_length=40),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='vrn',
            field=models.CharField(blank=True, help_text='VAT Registration Number', max_length=40),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='website',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
