# Generated by Django 5.0.1 on 2026-01-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('afisa_ugavi', 'Afisa Ugavi')], default='staff', max_length=15),
        ),
    ]
