# Generated by Django 5.0.1 on 2026-01-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('afisa_ugavi', 'Afisa Ugavi'), ('stock_controller', 'Stock Controller')], default='staff', max_length=20),
        ),
    ]
