# Generated by Django 5.2.15 on 2026-09-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('afisa_ugavi', 'Afisa Ugavi'), ('stock_controller', 'Stock Controller'), ('sales_rep', 'Sales Representative'), ('store_manager', 'Store Manager'), ('accountant', 'Accountant'), ('store_keeper', 'Store Keeper'), ('hr_officer', 'HR Officer'), ('hr_manager', 'HR Manager'), ('sales_credit_manager', 'Sales & Credit Manager'), ('cashier', 'Cashier')], default='staff', max_length=20),
        ),
    ]
