# Generated by Django 6.0 on 2026-01-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission percentage for sales of products in this category (e.g., 2.00 for 2%)', max_digits=5),
        ),
    ]
