# Generated by Django 6.0 on 2026-01-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_category_commission_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weight in kg', max_digits=10),
        ),
    ]
