# Generated by Django 6.0.5 on 2026-06-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_historicalproduct_historicalpurchase_historicalstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pcs'), ('item', 'Item'), ('bundle', 'Bundle'), ('box', 'Box'), ('carton', 'Carton'), ('dozen', 'Dozen'), ('bag', 'Bag'), ('roll', 'Roll'), ('kg', 'Kg'), ('ton', 'Ton'), ('meter', 'Meter'), ('litre', 'Litre'), ('set', 'Set'), ('pair', 'Pair'), ('other', 'Other')], default='pcs', max_length=20),
        ),
    ]
