# Generated by Django 6.0.5 on 2026-06-28 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_purchaseorderitem_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('fuel', 'Fuel'), ('spare_parts', 'Spare Parts'), ('repair', 'Repair'), ('service', 'Service'), ('insurance', 'Insurance'), ('license', 'License / Permit'), ('toll', 'Toll / Weighbridge'), ('parking', 'Parking'), ('fine', 'Fine / Penalty'), ('driver_allowance', 'Driver Allowance'), ('other', 'Other')], default='fuel', max_length=20)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor', models.CharField(blank=True, help_text='Station, garage, authority, etc.', max_length=120)),
                ('reference', models.CharField(blank=True, help_text='Receipt / invoice number', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(blank=True, help_text='Optional: link this cost to a specific trip/allocation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='inventory.truckallocation')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='inventory.truck')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
