# Generated by Django 5.2.15 on 2026-07-02 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_truckcost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='afisa_comment',
            field=models.TextField(blank=True, help_text="Afisa Ugavi's explanation for a discrepancy"),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='has_discrepancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='store_note',
            field=models.TextField(blank=True, help_text="Store Manager's note during cross-check"),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='delivered_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity actually delivered (set at store cross-check)', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('awaiting_check', 'Awaiting Store Check'), ('discrepancy', 'Discrepancy'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
