# Generated by Django 6.0.5 on 2026-09-05 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_purchaseorder_afisa_comment_purchaseorder_checked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='admin_note',
            field=models.TextField(blank=True, help_text="Admin's reason for confirming or rejecting a short delivery"),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Cumulative quantity accepted into stock across all delivery rounds'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('awaiting_check', 'Awaiting Store Check'), ('discrepancy', 'Discrepancy'), ('awaiting_admin', 'Awaiting Admin Decision'), ('partial', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='delivered_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity delivered in the latest cross-check round', null=True),
        ),
        migrations.CreateModel(
            name='DeliveryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('store_note', models.TextField(blank=True, help_text="Store Manager's note on this delivery")),
                ('has_discrepancy', models.BooleanField(default=False)),
                ('afisa_comment', models.TextField(blank=True, help_text="Afisa Ugavi's explanation for the shortfall")),
                ('commented_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('complete', 'Delivered in full'), ('pending_comment', 'Awaiting Afisa Ugavi comment'), ('pending_admin', 'Awaiting admin decision'), ('approved', 'Confirmed by admin'), ('rejected', 'Rejected by admin')], default='pending_comment', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, help_text="Admin's reason for confirming or rejecting")),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_checks', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_decisions', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='inventory.purchaseorder')),
            ],
            options={
                'verbose_name': 'Delivery Check',
                'ordering': ['-round_number'],
                'unique_together': {('purchase_order', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.PositiveIntegerField(help_text='What was still owed when this round was checked')),
                ('delivered_quantity', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, help_text="Store Manager's note on this item", max_length=255)),
                ('delivery_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.deliverycheck')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_lines', to='inventory.purchaseorderitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
