# Generated by Django 6.0.5 on 2026-09-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_backfill_received_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='goodsreceivednote',
            options={'ordering': ['-received_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date_purchased', '-id']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
    ]
