# Generated by Django 5.2.15 on 2026-09-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_branch_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Waiting for Delivery'), ('sent', 'Sent'), ('awaiting_check', 'Awaiting Store Check'), ('discrepancy', 'Discrepancy'), ('awaiting_admin', 'Awaiting Admin Decision'), ('partial', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
