# Generated by Django 6.0.5 on 2026-08-12 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the transaction')),
                ('receipt_number', models.CharField(blank=True, max_length=50, verbose_name='Receipt No')),
                ('efd_receipt_number', models.CharField(blank=True, max_length=50, verbose_name='EFD Receipt No')),
                ('customer_name', models.CharField(max_length=200)),
                ('tin', models.CharField(blank=True, help_text='Taxpayer Identification Number', max_length=40, verbose_name='TIN')),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('source_invoice', models.CharField(blank=True, editable=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRM Record',
                'verbose_name_plural': 'CRM Records',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['customer_name'], name='crm_custome_custome_2d32fb_idx'), models.Index(fields=['date'], name='crm_custome_date_a2ff6d_idx')],
            },
        ),
    ]
