# Generated by Django 6.0.5 on 2026-08-13 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_on', models.DateField()),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mobile', 'Mobile Money'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Bank slip, mobile money ref, cheque number', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_payments', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.customerrecord')),
            ],
            options={
                'verbose_name': 'CRM Payment',
                'verbose_name_plural': 'CRM Payments',
                'ordering': ['-paid_on', '-id'],
            },
        ),
    ]
