# Generated by Django 6.0.5 on 2026-08-13 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_crmpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crmpayment',
            name='from_credit',
            field=models.BooleanField(default=False, help_text="Settled from the customer's credit on account rather than new money received"),
        ),
        migrations.CreateModel(
            name='CrmCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(db_index=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('received_on', models.DateField()),
                ('source', models.CharField(choices=[('deposit', 'Deposit / advance'), ('overpayment', 'Overpayment on a sale'), ('adjustment', 'Adjustment')], default='deposit', max_length=20)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mobile', 'Mobile Money'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRM Credit',
                'verbose_name_plural': 'CRM Credits',
                'ordering': ['-received_on', '-id'],
            },
        ),
    ]
