# Generated by Django 6.0.5 on 2026-09-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_crmpayment_from_credit_crmcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmpayment',
            name='source_transaction',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='The sales transaction this payment was mirrored from', null=True, unique=True),
        ),
    ]
